services:
  - type: web
    name: taleforge
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/docs/
    envVars:
      - key: DEBUG
        value: "false"
      - key: SERVE_FRONTEND_FROM_DJANGO
        value: "true"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        sync: false
      - key: DB_SSL_REQUIRE
        value: "true"
      - key: RUN_MIGRATIONS_ON_START
        value: "true"
      - key: RUN_SEED_ON_DEPLOY
        value: "false"
      - key: ENABLE_DEMO_LOGIN_USERS
        value: "false"
      - key: ENABLE_GOOGLE_TRANSLATE_PROXY
        value: "true"
      - key: API_PAGE_SIZE
        value: "20"
      - key: THROTTLE_ANON
        value: 100/hour
      - key: THROTTLE_USER
        value: 600/hour
      - key: THROTTLE_AUTH
        value: 30/hour
      - key: THROTTLE_TRANSLATION
        value: 60/hour
